const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
const startOverlay=document.getElementById('startOverlay');
const endOverlay=document.getElementById('endOverlay');
const startButton=document.getElementById('startButton');
const restartButton=document.getElementById('restartButton');
const resultTitle=document.getElementById('resultTitle');
const resultText=document.getElementById('resultText');
const finalStats=document.getElementById('finalStats');
const timeText=document.getElementById('timeText');
const stressText=document.getElementById('stressText');
const fallText=document.getElementById('fallText');
const holdText=document.getElementById('holdText');

const C={bg:'#0b0f14',bg2:'#151b23',line:'rgba(235,240,245,.075)',blue:'#4fb8d8',rose:'#e06f8f',white:'#f8fafc',rock:'#a8a29e',danger:'#d97757',green:'#8bd3a7',gold:'#f0b86e'};
const W=[
 {name:'Pulse',color:C.blue,max:10,ammo:10,reload:.55,t:0,cd:.16,c:0,spd:640,dmg:1,count:1,spread:0,label:'fast'},
 {name:'Scatter',color:C.rose,max:5,ammo:5,reload:.95,t:0,cd:.38,c:0,spd:530,dmg:1,count:3,spread:.28,label:'wide'},
 {name:'Rail',color:C.gold,max:3,ammo:3,reload:1.45,t:0,cd:.62,c:0,spd:940,dmg:3,count:1,spread:0,label:'pierce'},
 {name:'Shield',color:C.green,max:2,ammo:2,reload:2.4,t:0,cd:.75,c:0,spd:0,dmg:0,count:0,spread:0,label:'bubble'}
];
const game={running:false,timer:0,score:0,hits:0,shake:0,spawn:0,angle:-Math.PI/2,drift:0,weapon:0,shield:0,rocks:[],shots:[],sparks:[],stars:[],controls:null,input:{forward:false,backward:false,weapon:false,turnLeft:false,turnRight:false,fire:false}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const cx=()=>canvas.width/2, cy=()=>canvas.height/2;
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars()} addEventListener('resize',resize); resize();
function stars(){game.stars=[];for(let i=0;i<90;i++)game.stars.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:.4+Math.random()*1.8,a:.25+Math.random()*.55})}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();ctx.fill();ctx.stroke()}
function resetWeapons(){W.forEach(w=>{w.ammo=w.max;w.t=0;w.c=0})}
function clearInput(){Object.keys(game.input).forEach(k=>game.input[k]=false);buttonState()}
function startGame(e){if(e){e.preventDefault();e.stopPropagation()}game.running=true;game.timer=0;game.score=0;game.hits=0;game.shake=0;game.spawn=.99;game.angle=-Math.PI/2;game.drift=0;game.weapon=0;game.shield=0;game.rocks=[];game.shots=[];game.sparks=[];clearInput();resetWeapons();stars();startOverlay.classList.add('hidden');endOverlay.classList.add('hidden');showControls(true);for(let i=0;i<3;i++)spawnRock()}
function endGame(msg){if(!game.running)return;game.running=false;clearInput();showControls(false);spark(cx(),cy(),C.danger,32);resultTitle.textContent='Game Over';resultText.textContent=msg;finalStats.innerHTML=`Survival Time: ${Math.floor(game.timer)}s<br>Asteroids Broken: ${game.score}<br>Hull Hits: ${game.hits}/3`;endOverlay.classList.remove('hidden')}
function spark(x,y,color,n=10){for(let i=0;i<n;i++){const a=Math.random()*6.283,s=45+Math.random()*180;game.sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,size:1.5+Math.random()*3.5,color})}}
function spawnRock(){const side=Math.floor(Math.random()*4);let x,y;if(side==0){x=-50;y=Math.random()*canvas.height}else if(side==1){x=canvas.width+50;y=Math.random()*canvas.height}else if(side==2){x=Math.random()*canvas.width;y=-50}else{x=Math.random()*canvas.width;y=canvas.height+50}const a=Math.atan2(cy()-y,cx()-x)+(-.5+Math.random());const sp=44+Math.random()*44+game.timer*1.1;const r=18+Math.random()*23;game.rocks.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r,hp:Math.ceil(r/17),rot:Math.random()*6.28,spin:-1+Math.random()*2})}
function selectWeapon(){game.weapon=(game.weapon+1)%W.length;spark(cx(),cy(),W[game.weapon].color,8)}
function fire(){const w=W[game.weapon];if(w.c>0||w.ammo<=0)return;w.c=w.cd;w.ammo--;if(w.name==='Shield'){game.shield=2.6;spark(cx(),cy(),w.color,24);return}for(let i=0;i<w.count;i++){const off=w.count===1?0:(i-1)*w.spread;const a=game.angle+off;game.shots.push({x:cx()+Math.cos(a)*29,y:cy()+Math.sin(a)*29,vx:Math.cos(a)*w.spd,vy:Math.sin(a)*w.spd,life:1.1,r:w.name==='Rail'?4:3,dmg:w.dmg,pierce:w.name==='Rail'?2:0,color:w.color})}spark(cx()+Math.cos(game.angle)*31,cy()+Math.sin(game.angle)*31,w.color,5)}
function update(dt){if(game.running){game.timer+=dt;if(game.input.forward)game.drift+=140*dt;if(game.input.backward)game.drift-=140*dt;game.drift*=Math.pow(.92,dt*60);if(game.input.turnLeft)game.angle-=3.2*dt;if(game.input.turnRight)game.angle+=3.2*dt;if(game.input.fire)fire();W.forEach(w=>{w.c=Math.max(0,w.c-dt);if(w.ammo<w.max){w.t+=dt;if(w.t>=w.reload){w.t=0;w.ammo++}}});if(game.shield>0)game.shield-=dt;game.spawn+=dt;if(game.spawn>Math.max(.42,1.15-game.timer*.012)){game.spawn=0;spawnRock()}updateRocks(dt);updateShots(dt);timeText.textContent=`${Math.floor(game.timer)}s`;stressText.textContent=`${3-game.hits}`;fallText.textContent=game.score;const w=W[game.weapon];holdText.textContent=`${w.name} ${w.ammo}/${w.max}`}updateSparks(dt);game.shake=Math.max(0,game.shake-dt*20)}
function updateRocks(dt){const pushX=Math.cos(game.angle)*game.drift*dt,pushY=Math.sin(game.angle)*game.drift*dt;for(let i=game.rocks.length-1;i>=0;i--){const r=game.rocks[i];r.x+=r.vx*dt-pushX;r.y+=r.vy*dt-pushY;r.rot+=r.spin*dt;if(Math.hypot(r.x-cx(),r.y-cy())<r.r+21){if(game.shield>0){spark(r.x,r.y,C.green,16);game.rocks.splice(i,1);game.score++;continue}game.hits++;game.shake=10;spark(cx(),cy(),C.danger,20);game.rocks.splice(i,1);if(game.hits>=3)endGame('The ship took too many hits.')}}}
function updateShots(dt){for(let i=game.shots.length-1;i>=0;i--){const s=game.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;let remove=s.life<=0||s.x<-60||s.x>canvas.width+60||s.y<-60||s.y>canvas.height+60;for(let j=game.rocks.length-1;j>=0&&!remove;j--){const r=game.rocks[j];if(Math.hypot(s.x-r.x,s.y-r.y)<s.r+r.r){r.hp-=s.dmg;spark(s.x,s.y,s.color,6);if(r.hp<=0){spark(r.x,r.y,s.color,18);game.rocks.splice(j,1);game.score++}if(s.pierce>0)s.pierce--;else remove=true}}if(remove)game.shots.splice(i,1)}}
function updateSparks(dt){for(let i=game.sparks.length-1;i>=0;i--){const p=game.sparks[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;p.life-=dt*2.2;if(p.life<=0)game.sparks.splice(i,1)}}
function bg(){const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,C.bg);g.addColorStop(.6,C.bg2);g.addColorStop(1,'#080b10');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=C.line;ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}ctx.globalAlpha=1;for(const s of game.stars){ctx.globalAlpha=s.a;ctx.fillStyle=C.white;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,6.28);ctx.fill()}ctx.globalAlpha=1}
function drawShip(){ctx.save();ctx.translate(cx(),cy());ctx.rotate(game.angle);ctx.shadowColor=C.blue;ctx.shadowBlur=10;ctx.fillStyle='rgba(17,24,39,.96)';ctx.strokeStyle='rgba(255,255,255,.38)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(30,0);ctx.lineTo(-18,-16);ctx.lineTo(-10,0);ctx.lineTo(-18,16);ctx.closePath();ctx.fill();ctx.stroke();if(Math.abs(game.drift)>10){ctx.fillStyle=C.gold;ctx.globalAlpha=clamp(Math.abs(game.drift)/180,.25,.9);const dir=game.drift>=0?-1:1;ctx.beginPath();ctx.moveTo(dir*20,0);ctx.lineTo(dir*35,-8);ctx.lineTo(dir*30,0);ctx.lineTo(dir*35,8);ctx.closePath();ctx.fill();ctx.globalAlpha=1}ctx.restore();if(game.shield>0){ctx.strokeStyle=C.green;ctx.lineWidth=3;ctx.globalAlpha=clamp(game.shield/2.6,.25,.8);ctx.beginPath();ctx.arc(cx(),cy(),39,0,6.28);ctx.stroke();ctx.globalAlpha=1}}
function drawRocks(){for(const r of game.rocks){ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.rot);ctx.fillStyle=C.rock;ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<9;i++){const a=i/9*6.28,rad=r.r*(.75+((i*17)%10)/35),x=Math.cos(a)*rad,y=Math.sin(a)*rad;if(i==0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}}
function drawShots(){for(const s of game.shots){ctx.fillStyle=s.color;ctx.shadowColor=s.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,6.28);ctx.fill();ctx.shadowBlur=0}}
function drawSparks(){for(const p of game.sparks){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life,0,6.28);ctx.fill()}ctx.globalAlpha=1}
function drawUI(){if(!game.running)return;const w=W[game.weapon];ctx.fillStyle='rgba(17,24,39,.82)';ctx.strokeStyle='rgba(255,255,255,.14)';ctx.lineWidth=1.5;rr(cx()-82,canvas.height-154,164,48,18);ctx.fillStyle=w.color;ctx.font='900 14px Arial';ctx.textAlign='center';ctx.fillText(`${w.name} · ${w.label}`,cx(),canvas.height-134);ctx.fillStyle=C.white;ctx.font='800 12px Arial';ctx.fillText(`Ammo ${w.ammo}/${w.max}`,cx(),canvas.height-116)}
function render(){ctx.save();if(game.shake)ctx.translate((Math.random()-.5)*game.shake,(Math.random()-.5)*game.shake);bg();drawShots();drawRocks();drawShip();drawSparks();drawUI();ctx.restore()}
function makeControls(){if(game.controls)return;const wrap=document.createElement('div');Object.assign(wrap.style,{display:'none',position:'absolute',inset:'0',zIndex:'30',pointerEvents:'none'});const top=[['backward','BACK'],['weapon','WEAPON'],['forward','FORWARD']];const bottom=[['turnLeft','LEFT'],['fire','FIRE'],['turnRight','RIGHT']];function add(k,label,row,i,color){const b=document.createElement('button');b.textContent=label;b.dataset.k=k;Object.assign(b.style,{position:'absolute',width:'31%',height:'56px',borderRadius:'18px',border:'1px solid rgba(255,255,255,.3)',background:'rgba(17,24,39,.92)',color,fontWeight:'900',fontSize:'12px',boxShadow:'0 12px 30px rgba(0,0,0,.38)',pointerEvents:'auto',touchAction:'none'});b.style.left=`${2+i*33}%`;b.style[row]='max(22px, env(safe-area-inset-bottom))';if(row==='top')b.style.top='78px';const down=e=>{e.preventDefault();e.stopPropagation();if(k==='weapon'&&!game.input.weapon)selectWeapon();if(k==='fire')fire();game.input[k]=true;buttonState()};const up=e=>{e.preventDefault();e.stopPropagation();game.input[k]=false;buttonState()};b.addEventListener('touchstart',down,{passive:false});b.addEventListener('pointerdown',down);b.addEventListener('touchend',up,{passive:false});b.addEventListener('touchcancel',up,{passive:false});b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);wrap.appendChild(b)}top.forEach((d,i)=>add(d[0],d[1],'top',i,C.blue));bottom.forEach((d,i)=>add(d[0],d[1],'bottom',i,C.rose));document.getElementById('gameScreen').appendChild(wrap);game.controls=wrap}
function showControls(show){makeControls();game.controls.style.display=show?'block':'none'}
function buttonState(){if(!game.controls)return;game.controls.querySelectorAll('button').forEach(b=>{const on=game.input[b.dataset.k];const color=['forward','backward','weapon'].includes(b.dataset.k)?C.blue:C.rose;b.style.background=on?color:'rgba(17,24,39,.92)';b.style.color=on?'#0b0f14':color;b.style.transform=on?'scale(.97)':'scale(1)'})}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function attachStart(el){['touchstart','pointerup','click'].forEach(ev=>el.addEventListener(ev,startGame,{passive:false}))}
attachStart(startButton);attachStart(restartButton);makeControls();showControls(false);render();